### ISSUE TITLE
Impossible to Change Review Table Colour

### ISSUE THREAD

**Issue by sprankhub** [firegento/firegento-germansetup#165]
Is there any reason for the `!important` at the beginning of `skin/frontend/base/default/css/germansetup/checkout.css`?

``` css
#checkout-review-table tfoot tr {
    background-color: #FBFAF6 !important;
}
```

The `germansetup.css` is included after other CSS files included via `addCss` in the `local.xml`. Hence, the `!important` makes it nearly impossible to change the colour of the review table in a nice way.
